services:
    grafana:
        image: grafana/grafana-enterprise
        user: "1000:1003"
        container_name: grafana
        restart: unless-stopped
        volumes: 
          - /project/seb_datascience/services/grafana/services-data:/var/lib/grafana
        ports:
          - 3000:3000