services:
    prometheus:
        image: prom/prometheus
        ports:
          - "9090:9090"
        volumes:
          - "/project/seb_datasience/services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
          - "/project/seb_datasience/services/prometheus/prometheus-data:/prometheus"
        