services:
    prometheus:
        image: prom/prometheus
        user: "1000:1003"
        network_mode: host
        volumes:
          - "/project/seb_datascience/services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
          - "/project/seb_datascience/services/prometheus/services-data:/prometheus"
          - "/project/seb_datascience/services/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml"
        restart: unless-stopped
    pushgateway:
        image: prom/pushgateway
        user: "1000:1003"
        network_mode: host
        restart: unless-stopped
    alertmanager:
        image: prom/alertmanager
        user: "1000:1003"
        network_mode: host
        volumes:
          - "/project/seb_datascience/services/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
        restart: unless-stopped
