global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 10s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'pushgateway'
    scheme: http
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9091']